# Generated by Django 5.2 on 2025-12-07 11:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0007_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='EmailLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Label Name')),
                ('color', models.CharField(choices=[('primary', 'Blue'), ('secondary', 'Gray'), ('success', 'Green'), ('danger', 'Red'), ('warning', 'Yellow'), ('info', 'Cyan'), ('light', 'Light'), ('dark', 'Dark')], default='primary', max_length=20, verbose_name='Label Color')),
                ('is_system', models.BooleanField(default=False, verbose_name='Is System Label')),
                ('system_type', models.CharField(blank=True, choices=[('inbox', 'Inbox'), ('sent', 'Sent'), ('drafts', 'Drafts'), ('important', 'Important'), ('trash', 'Trash'), ('spam', 'Spam'), ('starred', 'Starred')], max_length=20, null=True, verbose_name='System Label Type')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_labels', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Email Label',
                'verbose_name_plural': 'Email Labels',
                'ordering': ['-is_system', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='Subject')),
                ('body', models.TextField(verbose_name='Message Body')),
                ('body_html', models.TextField(blank=True, null=True, verbose_name='HTML Body')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('inbox', 'Inbox'), ('important', 'Important'), ('trash', 'Trash'), ('spam', 'Spam')], default='sent', max_length=20, verbose_name='Status')),
                ('is_read', models.BooleanField(default=False, verbose_name='Is Read')),
                ('is_starred', models.BooleanField(default=False, verbose_name='Is Starred/Important')),
                ('is_replied', models.BooleanField(default=False, verbose_name='Is Replied')),
                ('is_forwarded', models.BooleanField(default=False, verbose_name='Is Forwarded')),
                ('thread_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Thread ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('scheduled_send', models.DateTimeField(blank=True, null=True, verbose_name='Scheduled Send Time')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Read At')),
                ('bcc_recipients', models.ManyToManyField(blank=True, related_name='bcc_emails', to=settings.AUTH_USER_MODEL, verbose_name='BCC Recipients')),
                ('cc_recipients', models.ManyToManyField(blank=True, related_name='cc_emails', to=settings.AUTH_USER_MODEL, verbose_name='CC Recipients')),
                ('parent_email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='chat_app.email', verbose_name='Parent Email')),
                ('recipients', models.ManyToManyField(related_name='received_emails', to=settings.AUTH_USER_MODEL, verbose_name='Recipients')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_emails', to=settings.AUTH_USER_MODEL, verbose_name='Sender')),
                ('labels', models.ManyToManyField(blank=True, related_name='emails', to='chat_app.emaillabel', verbose_name='Labels')),
            ],
            options={
                'verbose_name': 'Email',
                'verbose_name_plural': 'Emails',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new_email', 'New Email'), ('email_read', 'Email Read'), ('email_replied', 'Email Replied'), ('email_forwarded', 'Email Forwarded'), ('email_deleted', 'Email Deleted'), ('email_starred', 'Email Starred')], max_length=20, verbose_name='Notification Type')),
                ('message', models.CharField(max_length=255, verbose_name='Notification Message')),
                ('is_read', models.BooleanField(default=False, verbose_name='Is Read')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='chat_app.email', verbose_name='Email')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_notifications', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Email Notification',
                'verbose_name_plural': 'Email Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Signature Name')),
                ('content', models.TextField(verbose_name='Signature Content')),
                ('content_html', models.TextField(blank=True, null=True, verbose_name='HTML Content')),
                ('is_default', models.BooleanField(default=False, verbose_name='Is Default Signature')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_signatures', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Email Signature',
                'verbose_name_plural': 'Email Signatures',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LoginActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('device', models.CharField(blank=True, max_length=50, null=True)),
                ('browser', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Login Activities',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='EmailAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='email_attachments/%Y/%m/%d/', verbose_name='Attachment File')),
                ('file_name', models.CharField(max_length=255, verbose_name='File Name')),
                ('file_size', models.BigIntegerField(verbose_name='File Size (bytes)')),
                ('file_type', models.CharField(max_length=100, verbose_name='File Type')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Uploaded At')),
                ('is_inline', models.BooleanField(default=False, verbose_name='Is Inline Attachment')),
                ('content_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Content ID (for inline)')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='chat_app.email', verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Email Attachment',
                'verbose_name_plural': 'Email Attachments',
                'ordering': ['uploaded_at'],
                'indexes': [models.Index(fields=['email', 'uploaded_at'], name='chat_app_em_email_i_5fef10_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmailContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('name', models.CharField(max_length=100, verbose_name='Contact Name')),
                ('company', models.CharField(blank=True, max_length=100, null=True, verbose_name='Company')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='Is Favorite')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('contact_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='as_email_contact', to=settings.AUTH_USER_MODEL, verbose_name='Contact User')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_contacts', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Email Contact',
                'verbose_name_plural': 'Email Contacts',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['user', 'is_favorite'], name='chat_app_em_user_id_07c974_idx'), models.Index(fields=['user', 'email'], name='chat_app_em_user_id_936161_idx')],
                'unique_together': {('user', 'email')},
            },
        ),
        migrations.CreateModel(
            name='EmailFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Filter Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('field', models.CharField(choices=[('sender', 'Sender'), ('recipient', 'Recipient'), ('subject', 'Subject'), ('body', 'Body')], max_length=20, verbose_name='Field to Check')),
                ('condition', models.CharField(choices=[('contains', 'Contains'), ('not_contains', 'Does not contain'), ('equals', 'Equals'), ('not_equals', 'Does not equal'), ('starts_with', 'Starts with'), ('ends_with', 'Ends with')], max_length=20, verbose_name='Condition')),
                ('value', models.CharField(max_length=255, verbose_name='Value to Match')),
                ('action', models.CharField(choices=[('move', 'Move to folder'), ('label', 'Apply label'), ('mark_read', 'Mark as read'), ('delete', 'Delete'), ('forward', 'Forward to'), ('reply', 'Auto-reply')], max_length=20, verbose_name='Action')),
                ('action_value', models.CharField(blank=True, max_length=255, null=True, verbose_name='Action Value')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_filters', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Email Filter',
                'verbose_name_plural': 'Email Filters',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='chat_app_em_user_id_e097d4_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='emaillabel',
            index=models.Index(fields=['user', 'is_system'], name='chat_app_em_user_id_9da5dc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='emaillabel',
            unique_together={('user', 'name')},
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['sender', 'created_at'], name='chat_app_em_sender__b88f75_idx'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['status', 'created_at'], name='chat_app_em_status_8d949d_idx'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['is_read', 'created_at'], name='chat_app_em_is_read_4ca066_idx'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['is_starred', 'created_at'], name='chat_app_em_is_star_114067_idx'),
        ),
        migrations.AddIndex(
            model_name='emailnotification',
            index=models.Index(fields=['user', 'is_read', 'created_at'], name='chat_app_em_user_id_f61c82_idx'),
        ),
        migrations.AddIndex(
            model_name='emailnotification',
            index=models.Index(fields=['created_at'], name='chat_app_em_created_18021b_idx'),
        ),
        migrations.AddIndex(
            model_name='emailsignature',
            index=models.Index(fields=['user', 'is_default'], name='chat_app_em_user_id_cc0c17_idx'),
        ),
    ]
